-- Resolve/Dismiss occurrence-lifecycle fix for cost_recommendations.
--
-- Problem: resolving or dismissing a recommendation only ever flipped its
-- status; the next scan's deleteAllActive()+createBulk() had no awareness of
-- RESOLVED/DISMISSED rows at all, so an unchanged AWS condition was silently
-- re-inserted as a brand-new ACTIVE row every scan, undoing the user's
-- action. Reserved Instance Opportunity findings are explicitly excluded
-- from this lifecycle (synthetic, fleet-level aggregate identity, not a
-- discrete resource) and are unaffected by this migration's semantics --
-- see backend/src/repositories/cost-recommendations.repository.ts.
--
-- occurrence_ended_at: NULL means "this RESOLVED/DISMISSED row's occurrence
-- is still open" (the default, safe state for every pre-existing row -- no
-- backfill needed, since NULL is already correct: a completed, successful
-- detector observation is required to set it, and none has run yet against
-- this column for historical rows). Once a successful, complete detector
-- observation confirms the underlying resource+issue is genuinely absent,
-- this is set once and never cleared; a later identical finding is then
-- treated as a new, independent occurrence rather than a resurrection of
-- the old one. ACTIVE rows never have this column set.
--
-- PLACEMENT NOTE: this file was initially placed in the ordinary
-- database/migrations/ path and a real (non-dry-run) `--execute-only`
-- attempt was made against production from there (SSM CommandId
-- 840a782e-c42a-4dbb-a18e-8f51eed26d0b, ExecutionStartDateTime
-- 2026-09-03T18:16:44.254Z) -- it failed with exactly
-- `42501: must be owner of table cost_recommendations`, rolled back
-- cleanly, and was never recorded in `schema_migrations`. A live,
-- read-only pg_class/pg_roles ownership audit in the same session
-- confirmed `cost_recommendations` is `postgres`-owned in production
-- while the ordinary runner connects as `devcontrol` (non-superuser,
-- owner of neither this table nor most of the schema). This file was
-- then moved into database/migrations-admin/ as a direct result of that
-- failure -- the same reclassification-after-failed-attempt
-- `202608270610_add_stripe_fields.sql` and
-- `202608312300_add_subscription_event_ordering.sql` already went
-- through. See database/migrations-admin/README.md's "Production
-- execution history" section for the full record. Only this note was
-- added; the ALTER TABLE / CREATE UNIQUE INDEX statements below are
-- byte-identical to the original ordinary-path version.
ALTER TABLE cost_recommendations
  ADD COLUMN occurrence_ended_at TIMESTAMPTZ NULL DEFAULT NULL;

-- Guards against duplicate ACTIVE rows for the same (org, resource, issue)
-- tuple under concurrent scans (manual analyze vs. the 6-hour cron, or two
-- overlapping manual scans) -- required for the reconciliation transaction's
-- INSERT ... ON CONFLICT ... DO NOTHING to have a target constraint.
--
-- Deliberately NOT CREATE INDEX CONCURRENTLY: this repository's migration
-- runner (database/migrate.js) wraps every migration in BEGIN/COMMIT
-- unconditionally, and PostgreSQL forbids CONCURRENTLY inside a transaction
-- block. A plain CREATE UNIQUE INDEX briefly locks the table against writes
-- while it builds.
--
-- DEPLOYMENT PRECONDITION -- must be verified before this migration is
-- applied to production (not verified by this migration or by the session
-- that authored it; this session has no production access):
--
--   SELECT organization_id, resource_id, issue, COUNT(*)
--   FROM cost_recommendations
--   WHERE status = 'ACTIVE'
--   GROUP BY organization_id, resource_id, issue
--   HAVING COUNT(*) > 1;
--
-- If this returns any rows, they must be reconciled (e.g. keep the newest,
-- resolve/delete the rest) before this migration can be applied -- it will
-- otherwise fail outright with a unique-violation during index creation.
CREATE UNIQUE INDEX idx_cost_recommendations_active_identity
  ON cost_recommendations (organization_id, resource_id, issue)
  WHERE status = 'ACTIVE';
